// GENERATED by scripts/stamp-map-version.mjs. Do not edit.
//
// Content hash of the descriptor directions and the zone tree. Every post
// is stamped with this, so a row can be told apart from one written under
// an older map. Run npm run scent:rezone after this changes.

export const EMBEDDING_VERSION = "d10f2a222f19";
export const ZONES_VERSION = "b504676ad4b5";
export const MAP_VERSION = "d10f2a222f19.b504676ad4b5";
